























.build/atmega328/LiquidTWI2/LiquidTWI2.o : lib/LiquidTWI2/LiquidTWI2.cpp
	@echo [93mLiquidTWI2/LiquidTWI2.cpp[0m
	@mkdir -p .build/atmega328/LiquidTWI2
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/LiquidTWI2/LiquidTWI2.cpp
include .build/atmega328/LiquidTWI2/LiquidTWI2.d



.build/atmega328/LiquidTWI2/libLiquidTWI2.a : .build/atmega328/LiquidTWI2/LiquidTWI2.o
	@echo [92mLinking libLiquidTWI2.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/atmega328/DallasTemperature/DallasTemperature.o : lib/DallasTemperature/DallasTemperature.cpp
	@echo [93mDallasTemperature/DallasTemperature.cpp[0m
	@mkdir -p .build/atmega328/DallasTemperature
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/DallasTemperature/DallasTemperature.cpp
include .build/atmega328/DallasTemperature/DallasTemperature.d



.build/atmega328/DallasTemperature/libDallasTemperature.a : .build/atmega328/DallasTemperature/DallasTemperature.o
	@echo [92mLinking libDallasTemperature.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/atmega328/DS1307RTC/DS1307RTC.o : lib/DS1307RTC/DS1307RTC.cpp
	@echo [93mDS1307RTC/DS1307RTC.cpp[0m
	@mkdir -p .build/atmega328/DS1307RTC
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/DS1307RTC/DS1307RTC.cpp
include .build/atmega328/DS1307RTC/DS1307RTC.d



.build/atmega328/DS1307RTC/libDS1307RTC.a : .build/atmega328/DS1307RTC/DS1307RTC.o
	@echo [92mLinking libDS1307RTC.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/atmega328/OneWire/OneWire.o : lib/OneWire/OneWire.cpp
	@echo [93mOneWire/OneWire.cpp[0m
	@mkdir -p .build/atmega328/OneWire
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/OneWire/OneWire.cpp
include .build/atmega328/OneWire/OneWire.d



.build/atmega328/OneWire/libOneWire.a : .build/atmega328/OneWire/OneWire.o
	@echo [92mLinking libOneWire.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/atmega328/Time/DateStrings.o : lib/Time/DateStrings.cpp
	@echo [93mTime/DateStrings.cpp[0m
	@mkdir -p .build/atmega328/Time
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/Time/DateStrings.cpp
include .build/atmega328/Time/DateStrings.d

.build/atmega328/Time/Time.o : lib/Time/Time.cpp
	@echo [93mTime/Time.cpp[0m
	@mkdir -p .build/atmega328/Time
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/Time/Time.cpp
include .build/atmega328/Time/Time.d



.build/atmega328/Time/libTime.a : .build/atmega328/Time/DateStrings.o .build/atmega328/Time/Time.o
	@echo [92mLinking libTime.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/atmega328/Wire/utility/twi.o : /usr/share/arduino/libraries/Wire/utility/twi.c
	@echo [93mWire/utility/twi.c[0m
	@mkdir -p .build/atmega328/Wire/utility
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/libraries/Wire/utility/twi.c
include .build/atmega328/Wire/utility/twi.d






.build/atmega328/Wire/Wire.o : /usr/share/arduino/libraries/Wire/Wire.cpp
	@echo [93mWire/Wire.cpp[0m
	@mkdir -p .build/atmega328/Wire
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/libraries/Wire/Wire.cpp
include .build/atmega328/Wire/Wire.d



.build/atmega328/Wire/libWire.a : .build/atmega328/Wire/utility/twi.o .build/atmega328/Wire/Wire.o
	@echo [92mLinking libWire.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/atmega328/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/atmega328/arduino/wiring_analog.d

.build/atmega328/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/atmega328/arduino/wiring.d

.build/atmega328/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/atmega328/arduino/wiring_digital.d

.build/atmega328/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/atmega328/arduino/wiring_shift.d

.build/atmega328/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/atmega328/arduino/WInterrupts.d

.build/atmega328/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/atmega328/arduino/wiring_pulse.d






.build/atmega328/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/atmega328/arduino/USBCore.d

.build/atmega328/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/atmega328/arduino/Print.d

.build/atmega328/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/atmega328/arduino/main.d

.build/atmega328/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/atmega328/arduino/IPAddress.d

.build/atmega328/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/atmega328/arduino/Stream.d

.build/atmega328/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/atmega328/arduino/HardwareSerial.d

.build/atmega328/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/atmega328/arduino/new.d

.build/atmega328/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/atmega328/arduino/HID.d

.build/atmega328/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/atmega328/arduino/WMath.d

.build/atmega328/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/atmega328/arduino/CDC.d

.build/atmega328/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/atmega328/arduino/Tone.d

.build/atmega328/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/atmega328/arduino
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/atmega328/arduino/WString.d



.build/atmega328/arduino/libarduino.a : .build/atmega328/arduino/wiring_analog.o .build/atmega328/arduino/wiring.o .build/atmega328/arduino/wiring_digital.o .build/atmega328/arduino/wiring_shift.o .build/atmega328/arduino/WInterrupts.o .build/atmega328/arduino/wiring_pulse.o .build/atmega328/arduino/USBCore.o .build/atmega328/arduino/Print.o .build/atmega328/arduino/main.o .build/atmega328/arduino/IPAddress.o .build/atmega328/arduino/Stream.o .build/atmega328/arduino/HardwareSerial.o .build/atmega328/arduino/new.o .build/atmega328/arduino/HID.o .build/atmega328/arduino/WMath.o .build/atmega328/arduino/CDC.o .build/atmega328/arduino/Tone.o .build/atmega328/arduino/WString.o
	@echo [92mLinking libarduino.a[0m
	@/usr/bin/avr-ar rcs $@ $^















.build/atmega328/src/controlo_temperatura.o : src/controlo_temperatura.cpp
	@echo [93msrc/controlo_temperatura.cpp[0m
	@mkdir -p .build/atmega328/src
	@/usr/bin/avr-g++ -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/LiquidTWI2 -Ilib/DallasTemperature -Ilib/DS1307RTC -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c src/controlo_temperatura.cpp
include .build/atmega328/src/controlo_temperatura.d







.build/atmega328/firmware.elf : .build/atmega328/src/controlo_temperatura.o .build/atmega328/LiquidTWI2/libLiquidTWI2.a .build/atmega328/DallasTemperature/libDallasTemperature.a .build/atmega328/DS1307RTC/libDS1307RTC.a .build/atmega328/OneWire/libOneWire.a .build/atmega328/Time/libTime.a .build/atmega328/Wire/libWire.a .build/atmega328/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/atmega328/firmware.hex : .build/atmega328/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/atmega328/src/dependencies.d .build/atmega328/arduino/dependencies.d .build/atmega328/LiquidTWI2/dependencies.d .build/atmega328/DallasTemperature/dependencies.d .build/atmega328/OneWire/dependencies.d .build/atmega328/Wire/dependencies.d .build/atmega328/DS1307RTC/dependencies.d .build/atmega328/Time/dependencies.d

all : .build/atmega328/firmware.hex
	@true

