







	



.build/atmega328/Time/DateStrings.d : lib/Time/DateStrings.cpp
	@mkdir -p .build/atmega328/Time
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/LiquidTWI2 -Ilib/DS1307RTC -Ilib/DallasTemperature -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata  -MM $^ > $@
	
	@printf ".build/atmega328/Time/DateStrings.d .build/atmega328/Time/" | cat - $@ > $@~ && mv $@~ $@

.build/atmega328/Time/Time.d : lib/Time/Time.cpp
	@mkdir -p .build/atmega328/Time
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/LiquidTWI2 -Ilib/DS1307RTC -Ilib/DallasTemperature -Ilib/OneWire -Ilib/Time -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Firmata  -MM $^ > $@
	
	@printf ".build/atmega328/Time/Time.d .build/atmega328/Time/" | cat - $@ > $@~ && mv $@~ $@



.build/atmega328/Time/dependencies.d : .build/atmega328/Time/DateStrings.d .build/atmega328/Time/Time.d
	@echo [96mScanning dependencies of Time[0m
	@mkdir -p .build/atmega328/Time
	@cat $^ > $@;

all : .build/atmega328/Time/dependencies.d
	@true

